
- name: Deploy to cPanel
  uses: appleboy/scp-action@v0.1.7
  with:
    host: ${{ secrets.CPANEL_HOST }}       # eg: server376.web-hosting.com
    username: ${{ secrets.CPANEL_USER }}   # eg: ecehidmk
    key: ${{ secrets.CPANEL_SSH_KEY }}     # secret ou te ajoute
    port: 21098                            # port SFTP cPanel
    source: "dist/*"                       # katab lokal build ou
    target: "/public_html/"                # katab sou cPanel
    rm: true                               # efase target avan upload
    overwrite: true                        # overwrite fichye ki deja egziste
    debug: true
