- name: Upload files via SCP
  uses: appleboy/scp-action@v0.1.7
  with:
    host: ${{ secrets.CPANEL_HOST }}
    username: ${{ secrets.SSH_USER }}
    key: ${{ secrets.CPANEL_SSH_KEY }}
    passphrase: ${{ secrets.KEY_PASSPHRASE }}
    port: ${{ secrets.CPANEL_PORT }}
    source: "dist/*"
    target: "/home/sbtechn/public_html/"
    overwrite: true
