      - name: Deploy to cPanel
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          passphrase: ${{ secrets.CPANEL_KEY_PASSPHRASE }}
          port: 21098
          source: "dist/*"
          target: "/public_html/"
          rm: true
          overwrite: true
          debug: true
